### ISSUE TITLE
Odooghost freeze when trying to clone an unexisting repository

### ISSUE THREAD

**Issue by BurkhalterY** [remyz17/odooghost#10]
Odooghost freeze when trying to clone an unexisting repository.

Exemple of stack:

```yaml
name: Test
services:
  odoo:
    version: 16.0
    cmdline: "--workers=2"
    addons:
      - type: remote
        mode: mount
        origin: https://github.com/unexisting/repository.git
        branch: "16.0"
        path: /home/ybu/docker/git/16.0/unexisting/repository
  db:
    type: local
    version: 14
 ```
