### ISSUE TITLE
Port binding on Windows

### ISSUE THREAD

**Issue by BurkhalterY** [remyz17/odooghost#14]
On Windows (10), it seems that specifying the port in the stack config is mandatory, because otherwise the port remains not bound in Docker.

E.g.

```yaml
name: TestWindows
services:
  odoo:
    version: 17.0
    service_port: 8069
  db:
    type: local
    version: 14
```

On Ubuntu, it worked directly.
